Repository CharVstack/CharV-backend, pull requests merged in 2022-11, with the labels that each got.

#46 CVS-151 開発ルールの整備
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
Labels: documentation

#48 CVS-156 リリースノートの設定ファイルの作成
  .github/release.yml
Labels: documentation

#58 CVS-163 internalとpkg内を整理
  cmd/server/main.go
  go.mod
  go.sum
  handler/handler.go
  internal/host/cpu/cpu.go
  internal/host/memory/memory.go
  internal/host/storage/storage.go
  pkg/host/cpu/cpu.go
  pkg/host/host.go
  pkg/host/memory/memory.go
  pkg/host/storage/pool.go
  pkg/host/storage/pool_test.go
  pkg/host/storage/storage.go
  pkg/qemu/disk.go
  pkg/qemu/disk_test.go
  pkg/qemu/type.go
  pkg/qemu/vm.go
  pkg/qemu/vm_test.go
  pkg/util/memory.go
Labels: refactoring

#57 CVS-161 グローバルコンフィグを共通化して格納
  cmd/server/main.go
  handler/handler.go
Labels: enhancement

#60 CVS-166 APIスキーマ定義の変更に対応
  handler/handler.go
  pkg/host/host.go
  pkg/host/memory/memory.go
  pkg/qemu/vm.go
  pkg/qemu/vm_test.go
  test/resources/machines/ubuntu.json
Labels: bug

#62 CVS-170 Deploy test coverage in github pages
  .github/workflows/coverage.yaml
  .gitignore
  Makefile
Labels: documentation, enhancement

#63 CVS-170 fix script error
  .github/workflows/coverage.yaml
Labels: bug

#64 CVS-171 動作しない可能性があるWorkflowを修正
  .github/workflows/coverage.yaml
  .github/workflows/test.yml
  .gitignore
  Makefile
Labels: bug

#65 CVS-170 Add coverage badge in README.md
  README.md
  middleware/log.go
Labels: documentation

#66 CVS-172 ホットリロードをできるようにする
  .air.toml
  Makefile
  README.md
Labels: documentation, enhancement

#69 CVS-174 電源関連の前提の作成
  .env.sample
  cmd/server/main.go
  handler/handler.go
  test/resources/socks/0bfb8def-86ed-4b9d-8826-66a6ab1c1491.sock
Labels: enhancement

#70 CVS-175 vm作成時にsocketが生成されるように更新
  handler/handler.go
  pkg/qemu/type.go
  pkg/qemu/vm.go
Labels: enhancement

#71 CVS-137 VMの電源状態の取得
  handler/handler.go
  pkg/qemu/vm.go
  pkg/qemu/vm_test.go
  pkg/util/search.go
Labels: enhancement

#72 CVS-149 backendで電源操作用のエンドポイントを作成
  go.mod
  go.sum
  handler/handler.go
  pkg/qemu/vm.go
Labels: enhancement

#74 CVS-183 codecovを使う
  .github/workflows/coverage.yaml
  .github/workflows/test.yml
  Makefile
  README.md
Labels: enhancement

#80 CVS-188 renovateの設定を修正
  renovate.json
Labels: bug
