Repository CharVstack/CharV-backend, pull requests merged in 2022-12, with the labels that each got.

#84 CVS-186 backendでstart用のエンドポイントを作成
  cmd/server/main.go
  go.mod
  go.sum
  pkg/qemu/vm.go
Labels: enhancement

#75 CVS-149 エラー出力を強化
  pkg/qemu/vm.go
  pkg/qemu/vm_test.go
Labels: enhancement

#83 CVS-190 ripzapの代わりにzapを使う
  Makefile
  cmd/server/develop.go
  cmd/server/main.go
  cmd/server/production.go
  go.mod
  go.sum
  middleware/log.go
Labels: enhancement

#85 CVS-191 development環境のデプロイワークフロー
  .github/workflows/cd.yaml
Labels: enhancement

#90 CVS-197 WIP: secrets の変数名を修正
  .github/workflows/cd.yaml
Labels: bug

#91 CVS-197 WIP: secrets が読み込めていないのを修正
  .github/workflows/cd.yaml
Labels: bug

#92 CVS-197 WIP: シェルスクリプトの場所を間違えていたのを修正
  .github/workflows/cd.yaml
Labels: bug

#89 CVS-196 rebootのエンドポイントを追加
  handler/handler.go
  pkg/qemu/type.go
  pkg/qemu/vm.go
Labels: enhancement

#95 CVS-204 makefileの修正
  Makefile
Labels: bug

#96 CVS-205 バイナリの転送方法に失敗するバグを修正
  .github/workflows/cd.yaml
Labels: bug

#100 CVS-210 runner の実行環境を変更
  .github/workflows/cd.yaml
Labels: enhancement

#102 CVS-211 production環境への自動デプロイを作成
  .github/workflows/deploy-prd.yaml
  .github/workflows/deploy-stg.yaml
Labels: enhancement

#104 CVS-215 prd 環境へのデプロイイベントのトリガーを修正
  .github/workflows/deploy-prd.yaml
Labels: bug

#103 CVS-214 リリースノートに載せる authors から renovate を除外
  .github/release.yml
Labels: documentation

#106 CVS-220 vm削除の処理を実装
  handler/handler.go
  pkg/qemu/vm.go
Labels: enhancement

#109 CVS-232 リリースするバイナリに環境フラグを付与
  .github/workflows/deploy-prd.yaml
  .github/workflows/deploy-stg.yaml
Labels: enhancement
